Add docker image creation script

diff --git a/.github/workflows/push-openwrt-to-docker-hub.yml b/.github/workflows/push-openwrt-to-docker-hub.yml
--- a/.github/workflows/push-openwrt-to-docker-hub.yml
+++ b/.github/workflows/push-openwrt-to-docker-hub.yml
@@ -25,6 +25,8 @@ on:
         default: "ophub/openwrt-aarch64:latest"
 
 env:
+  TZ: America/New_York
+  MAKE_DOCKER_SH: config-openwrt/docker/make_docker_image.sh
   DOCKER_OUTPATH: out
 
 jobs:
@@ -41,24 +43,40 @@ jobs:
         if: (!cancelled())
         run: |
           # Get OpenWrt file
-          openwrt_url="$(curl --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" | grep -o "OpenWrt_.*${{ inputs.source_branch }}.*/.*rootfs.tar.gz" | head -n 1)"
+          openwrt_url="$(curl \
+                            --header "authorization: Bearer ${{ secrets.GH_TOKEN }}" \
+                            -s "https://api.github.com/repos/${GITHUB_REPOSITORY}/releases" |
+                            grep -o "OpenWrt_.*${{ inputs.source_branch }}.*/.*rootfs.tar.gz" |
+                            head -n 1
+                        )"
           [[ -z "${openwrt_url}" ]] && echo -e "OpenWrt file not found!" && exit 1
-          rm -rf ${{ env.DOCKER_OUTPATH }} 2>/dev/null && mkdir -p ${{ env.DOCKER_OUTPATH }}
-          wget -q "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -O "${{ env.DOCKER_OUTPATH }}/openwrt-armvirt-64-default-rootfs.tar.gz"
-          #
+
+          [[ -d "openwrt" ]] || mkdir -p openwrt
+          wget -q "https://github.com/${GITHUB_REPOSITORY}/releases/download/${openwrt_url}" -O "openwrt/openwrt-armvirt-64-default-rootfs.tar.gz"
+          [[ "${?}" -ne "0" ]] && echo "OpenWrt file download failed." && exit 1
+          echo "status=success" >> ${GITHUB_OUTPUT}
+
+      - name: Make docker image
+        id: make
+        if: ${{ steps.down.outputs.status }} == 'success' && !cancelled()
+        run: |
+          # Make docker image
+          chmod +x ${MAKE_DOCKER_SH}
+          ${MAKE_DOCKER_SH}
+
           # Generate Dockerfile
           docker_envfile="${{ env.DOCKER_OUTPATH }}/Dockerfile"
           echo 'FROM scratch' >${docker_envfile}
-          echo 'ADD openwrt-armvirt-64-default-rootfs.tar.gz /' >>${docker_envfile}
+          echo 'ADD docker-armvirt-64-default-rootfs.tar.gz /' >>${docker_envfile}
           echo 'EXPOSE 22 53 80 443 7681' >>${docker_envfile}
           echo 'ENTRYPOINT ["/sbin/init"]' >>${docker_envfile}
-          #
+
           sync && echo -e "Current ${{ env.DOCKER_OUTPATH }} directory status: \n$(ls ${{ env.DOCKER_OUTPATH }} -l)"
           echo "status=success" >> ${GITHUB_OUTPUT}
 
       - name: Set up QEMU
         id: qemu
-        if: (!cancelled())
+        if: ${{ steps.make.outputs.status }} == 'success' && !cancelled()
         uses: docker/setup-qemu-action@v2
 
       - name: Set up Docker Buildx
